# Site settings
title: A coding love story
header-img: img/home-bg.png
email: melissaeaybar@gmail.com
copyright_name: Tamiyo22
description: > # this means to ignore newlines until "baseurl:"
  for (var code=0; code<Infinity; code++) {}
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  Tamiyo22
learn_profile: Tamiyo22
email_username: melissaeaybar@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
